---
title: "hent-ssb-data.Rmd"
author: "Jonathan"
date: "12/30/2021"
output: html_document
---

```{r}
library(PxWebApiData)
library(tidyverse)
```

```{r}
load("knr.Rdata")
```

## Hente data om gjennomsnittlig kvadratmeterpris for eneboliger

```{r}
pm2_raw <- ApiData(
  urlToData = "06035",
  Region = knr,
  ContentsCode = "KvPris",
  Boligtype = "01",
  Tid = c(as.character(2006:2017))
)
```

### Droppe variabler og endre navn

```{r}
pm2 <- pm2_raw$dataset %>%
  select(-Boligtype, -ContentsCode) %>%
  rename(
    knr = Region,
    aar = Tid,
    pm2 = value
  )
```

### Endre navn på elementet

```{r}
names(pm2_raw)[[1]] <- "desc"
```

### Legge til kommunenavnene til pm2 som variablen *knavn*

```{r}
pm2 <- pm2 %>%
  mutate(
    knavn = pm2_raw$desc$region
  )
```

### Fjerne paranteser i knavn

```{r}
# se help str_replace.str_replace_all(string, pattern, replacement). Vi skal altså
# sende inn en tekststreng, vår eksisterende knavn variabel, bruke en regex for å matche de
# parentesene vi vil bli kvitt. Det er denne rgex-en vi har i moenster. Til slutt må vi angi
# det vi vil erstatte teksen med. I vårt tilfelle vil vi bare slette så replacement er ""
# som angir ingenting. Legg ut i et objekt tmp først for å teste at riktig, så endre til 
# pm2 <- pm2 %>% .... For så å oppdatere pm2 med nye navn
# Fyll inn argumentene til str_replace under. Sjekk at tmp ser ut slik du ønsker. Bytt så ut
# tmp <- pm2 %>% ...  med pm2 <- pm2 %>% ...
pm2 <- pm2 %>% 
  # oppdaterer knavn så bruker mutate
  mutate(
  knavn = str_replace(
    string = knavn,
    pattern = '\\s*\\([-\\d\\s]*\\)\\s*$' ,
    replacement = ""
  )
  )
```


## Finn kommunenummer for de kommunene som har complete.cases() fra 2006

```{r}
# Lager tibble med knr for de kommuner som har 
# complete.cases i perioden 2006-2017
knr_c.c <- pm2 %>%
  mutate(
    c.c = complete.cases(.)
  ) %>%
  group_by(knr) %>%
  summarise(sum_c.c = sum(c.c)) %>%
  filter(
    sum_c.c == max(sum_c.c)
  )
```

```{r}
# Lager en vector med knr for complete cases
knr_c.c <- knr_c.c$knr
```

### Bruke knr_cc til å redusere pm2 til kommunene som har "complete cases".

```{r}
pm2 <- pm2 %>%
  filter(
    knr %in% knr_c.c
  )
```

```{r}
dim(pm2)
```

```{r, echo = FALSE}
# Jonathan. Velg Restart R and clear ouput fra Run drop-down menyen. Trykk så på PIl-ned-strek
# (Run all chunks above) borte i høyre hjørne i denne chunken. Får du fremdels ikke 2364 4 ?
#siste
```

